
CREATE USER usua1 IDENTIFIED BY prueba6
CREATE USER usua2 IDENTIFIED BY prueba5

GRANT DROP USER TO usua1;

GRANT CREATE SESSION TO usua1;


DROP USER usua2;


GRANT SELECT, INSERT ON countries TO usua1;

INSERT INTO countries VALUES (‘IT’, ‘ITALIA’,3);

GRANT DELETE ON countries TO usua1;

GRANT CREATE USER, GRANT ANY PRIVILEGE TO usua1;

CREATE ROLE Admin;
GRANT CREATE USER, CREATE ROLE TO Admin;
GRANT SELECT, INSERT ON Jobs to Admin;
GRANT Admin to usua1;
   
REVOKE INSERT FROM Admin;

REVOKE Admin FROM usua1;


DROP ROLE Admin;
