SELECT * FROM bd_academic_sessions;
SELECT * FROM bd_departments;
SELECT * FROM bd_courses;
SELECT * FROM bd_exam_results;
SELECT * FROM bd_exam_types;
SELECT * FROM bd_exams;
SELECT * FROM bd_faculty;
SELECT * FROM bd_faculty_course_details;
SELECT * FROM bd_faculty_login_details;
SELECT * FROM bd_parent_information;
SELECT * FROM bd_student_attendance;
SELECT * FROM bd_student_course_details;
SELECT * FROM bd_students;
SELECT STUDENT_ID, course_id, exam_id, exam_grade FROM bd_exam_results;
SELECT STUDENT_ID, num_work_days, exam_eligibility FROM bd_student_attendance;
SELECT faculty_id, login_date_time from bd_faculty_login_details;
SELECT dept_name, dept_head from bd_departments;
SELECT student_id ||': FIRST NAME IS '|| first_name from bd_students;
SELECT distinct exam_type from bd_exams;
SELECT student_id, exam_id, (exam_grade -5) from bd_exam_results;
SELECT student_id, ((num_days_off/num_work_days)*100) ,exam_eligibility from bd_student_attendance;
SELECT 'La dirección de correo de ' || first_name ||' es ' || email AS "Direcciones de email" FROM bd_students;
SELECT 'El director del departamento de ' || dept_name ||' es ' || dept_head AS "Departamento y director" FROM bd_departments;
SELECT DISTINCT dept_id FROM bd_courses;